In [1]:
import pandas as pd
from google.cloud import bigquery
import db_dtypes as db 
import os

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] ='D:/mythings/BigqueryAPI/core-waters-440019-c6-3e5d7103ad61.json'

In [2]:
# Create a "Client" object
client = bigquery.Client()

# Construct a reference to the "hacker_news" dataset
dataset_ref = client.dataset("hacker_news", project="bigquery-public-data")

# API request - fetch the dataset
dataset = client.get_dataset(dataset_ref)

In [3]:
# List all the tables in the "hacker_news" dataset
tables = list(client.list_tables(dataset))
# Print names of all tables in the dataset (there are four!)
for table in tables:  
    print(table.table_id)

full

In [4]:
# Construct a reference to the "full" table
table_ref = dataset_ref.table("full")

# API request - fetch the table
table = client.get_table(table_ref)

In [5]:
table.schema

[SchemaField('title', 'STRING', 'NULLABLE', None, 'Story title', (), None),
 SchemaField('url', 'STRING', 'NULLABLE', None, 'Story url', (), None),
 SchemaField('text', 'STRING', 'NULLABLE', None, 'Story or comment text', (), None),
 SchemaField('dead', 'BOOLEAN', 'NULLABLE', None, 'Is dead?', (), None),
 SchemaField('by', 'STRING', 'NULLABLE', None, "The username of the item's author.", (), None),
 SchemaField('score', 'INTEGER', 'NULLABLE', None, 'Story score', (), None),
 SchemaField('time', 'INTEGER', 'NULLABLE', None, 'Unix time', (), None),
 SchemaField('timestamp', 'TIMESTAMP', 'NULLABLE', None, 'Timestamp for the unix time', (), None),
 SchemaField('type', 'STRING', 'NULLABLE', None, 'type of details (comment comment_ranking poll story job pollopt)', (), None),
 SchemaField('id', 'INTEGER', 'NULLABLE', None, "The item's unique id.", (), None),
 SchemaField('parent', 'INTEGER', 'NULLABLE', None, 'Parent comment ID', (), None),
 SchemaField('descendants', 'INTEGER', 'NULLABLE', None, 'Number of story or poll descendants', (), None),
 SchemaField('ranking', 'INTEGER', 'NULLABLE', None, 'Comment ranking', (), None),
 SchemaField('deleted', 'BOOLEAN', 'NULLABLE', None, 'Is deleted?', (), None)]

In [6]:
client.list_rows(table, max_results=5).to_dataframe()

,title,url,text,dead,by,score,time,timestamp,type,id,parent,descendants,ranking,deleted
0,None,None,None,<NA>,None,<NA>,1438497614,2015-08-02 06:40:14+00:00,story,9990003,<NA>,<NA>,<NA>,<NA>
1,None,None,None,<NA>,None,<NA>,1438497660,2015-08-02 06:41:00+00:00,story,9990004,<NA>,<NA>,<NA>,<NA>
2,None,None,None,<NA>,None,<NA>,1438501105,2015-08-02 07:38:25+00:00,story,9990077,<NA>,<NA>,<NA>,<NA>
3,None,None,None,<NA>,None,<NA>,<NA>,NaT,story,99902,<NA>,<NA>,<NA>,<NA>
4,None,None,None,<NA>,None,<NA>,1438507076,2015-08-02 09:17:56+00:00,story,9990213,<NA>,<NA>,<NA>,<NA>

In [7]:
# Preview the first five entries in the "by" column of the "full" table
client.list_rows(table, selected_fields=table.schema[:1], max_results=5).to_dataframe()

  title
0  None
1  None
2  None
3  None
4  None