In [21]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, root_mean_squared_error, mean_absolute_error

In [22]:
test = pd.read_csv('D:/mythings/Dataset/HousePrice/Housing Prices Competition for Kaggle Learn Users/test.csv')
train = pd.read_csv('D:/mythings/Dataset/HousePrice/Housing Prices Competition for Kaggle Learn Users/train.csv')

In [23]:
test.describe()

                Id   MSSubClass  ...       MoSold       YrSold
count  1459.000000  1459.000000  ...  1459.000000  1459.000000
mean   2190.000000    57.378341  ...     6.104181  2007.769705
std     421.321334    42.746880  ...     2.722432     1.301740
min    1461.000000    20.000000  ...     1.000000  2006.000000
25%    1825.500000    20.000000  ...     4.000000  2007.000000
50%    2190.000000    50.000000  ...     6.000000  2008.000000
75%    2554.500000    70.000000  ...     8.000000  2009.000000
max    2919.000000   190.000000  ...    12.000000  2010.000000

[8 rows x 37 columns]

In [24]:
train.describe()
# outliers may lie in LotFrontage, LotArea, MasVnrArea, BsmtFinSF1, BsmtFinSF2, BsmtUnfSF,
# TotalBsmtSF

                Id   MSSubClass  ...       YrSold      SalePrice
count  1460.000000  1460.000000  ...  1460.000000    1460.000000
mean    730.500000    56.897260  ...  2007.815753  180921.195890
std     421.610009    42.300571  ...     1.328095   79442.502883
min       1.000000    20.000000  ...  2006.000000   34900.000000
25%     365.750000    20.000000  ...  2007.000000  129975.000000
50%     730.500000    50.000000  ...  2008.000000  163000.000000
75%    1095.250000    70.000000  ...  2009.000000  214000.000000
max    1460.000000   190.000000  ...  2010.000000  755000.000000

[8 rows x 38 columns]

In [25]:
train.head()

   Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 81 columns]

In [ ]:
missing_value_counts = train.isnull().sum()
missing_value_counts

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

:

In [27]:
missing_value_features = ['LotFrontage','Alley','MasVnrType','MasVnrArea','BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2','Electrical','FireplaceQu','GarageType','GarageYrBlt','GarageFinish','GarageQual','GarageCond','PoolQC','Fence','MiscFeature']
train[missing_value_features]

      LotFrontage Alley MasVnrType  ...  PoolQC  Fence MiscFeature
0            65.0   NaN    BrkFace  ...     NaN    NaN         NaN
1            80.0   NaN        NaN  ...     NaN    NaN         NaN
2            68.0   NaN    BrkFace  ...     NaN    NaN         NaN
3            60.0   NaN        NaN  ...     NaN    NaN         NaN
4            84.0   NaN    BrkFace  ...     NaN    NaN         NaN
...           ...   ...        ...  ...     ...    ...         ...
1455         62.0   NaN        NaN  ...     NaN    NaN         NaN
1456         85.0   NaN      Stone  ...     NaN  MnPrv         NaN
1457         66.0   NaN        NaN  ...     NaN  GdPrv        Shed
1458         68.0   NaN        NaN  ...     NaN    NaN         NaN
1459         75.0   NaN        NaN  ...     NaN    NaN         NaN

[1460 rows x 19 columns]

### Define the reasons why missing values in each column
* Missing values in LotFrontage are because of not being recorded
* In Alley, there is no clear evidence showing that values are missing because of lack of record 
    * --> therefore, missing values in this column should be filled with NA
* If values in MasVnrType are missing, it will be filled with None
* If values in MasVnrArea are missing and values in MasVnrType are misisng/none, it will be filled with 0
* Missing values in BsmtQal, BsmtCond, BsmtExposure, BsmtFinType1, BsmtFinSF1, BsmtFinType2, BsmtFinSF2
having relationship with each other.
    * Filling the missing values with NA - NA - NA - 0 - NA
* 1 missing value in Electrical is due to lack of record
* If values in Fireplace are 0, then values in FireplaceQu will be filled with NA
* If GarageType