In [1]:
import pandas as pd
import numpy as np
from selenium import webdriver
from selenium.webdriver.edge.service import Service
from selenium.webdriver.common.by import By
from time import sleep
import random
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
import msedgedriver
from selenium.common.exceptions import JavascriptException, NoSuchElementException, TimeoutException

In [2]:
edgeService = msedgedriver.install()
options = webdriver.EdgeOptions()
options.add_argument("--auto-open-devtools-for-tabs")
options.add_argument('--headless')
options.add_argument('inprivate')

your edge version is
131.0.2903.86
131.0.2903.86
driver is upto date and file is in the right place

In [14]:
driver = webdriver.Edge(service=edgeService, options= options)
driver.get('https://www.vgchartz.com/games/games.php?page=1&order=Sales&ownership=Both&direction=DESC&showtotalsales=1&shownasales=1&showpalsales=1&showjapansales=1&showothersales=1&showpublisher=1&showdeveloper=0&showreleasedate=1&showlastupdate=1&showvgchartzscore=0&showcriticscore=1&showuserscore=0&showshipped=1')
sleep(random.randint(3,10))

i = 4
n = 1
elems = driver.find_element(By.XPATH,f'//*[@id="generalBody"]/table[1]/tbody/tr[{i}]/td[%d]'%n)
test0 = []
test0.append(elems.text)

In [15]:
games_titles, games_links, publishers, total_shipped, released_date, last_updated = [], [], [], [],[],[]

In [16]:
count = 1
for page in range(1,51):
    print(f'Current Page {page}')
    try:
        for i in range(4,54):
            n = 3
            while n <= 14:
                elems_names = driver.find_element(By.XPATH,f'//*[@id="generalBody"]/table[1]/tbody/tr[{i}]/td[%d]/a[1]'%n)
                games_titles.append(elems_names.text)
                games_links.append(elems_names.get_attribute('href'))
                n +=2
                elems = driver.find_element(By.XPATH,f'//*[@id="generalBody"]/table[1]/tbody/tr[{i}]/td[%d]'%n)
                publishers.append(elems.text)
                n +=2
                elems = driver.find_element(By.XPATH,f'//*[@id="generalBody"]/table[1]/tbody/tr[{i}]/td[%d]'%n)
                total_shipped.append(elems.text)
                n += 6
                elems = driver.find_element(By.XPATH,f'//*[@id="generalBody"]/table[1]/tbody/tr[{i}]/td[%d]'%n)
                released_date.append(elems.text)
                n +=1
                elems = driver.find_element(By.XPATH,f'//*[@id="generalBody"]/table[1]/tbody/tr[{i}]/td[%d]'%n)
                last_updated.append(elems.text)
                if n == 14:
                    break
        print(f'Crawling data page {page}')
        count +=1
        #driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        if count == 12:
            count = 6
            next_page = driver.find_element(By.XPATH,'//*[@id="generalBody"]/table[2]/tbody/tr/th[2]/span[%d]/a'%count)
            driver.execute_script("arguments[0].click();", next_page)
            print(f'Clicked on button page {page+1}!')
            sleep(random.randint(5,10))
        else:
            next_page = driver.find_element(By.XPATH,'//*[@id="generalBody"]/table[2]/tbody/tr/th[2]/span[%d]/a'%count)
            driver.execute_script("arguments[0].click();", next_page)
            print(f'Clicked on button page {page+1}!')
            sleep(random.randint(5,10))

    except NoSuchElementException:
        continue

Current Page 1
Crawling data page 1
Clicked on button page 2!
Current Page 2
Crawling data page 2
Clicked on button page 3!
Current Page 3
Crawling data page 3
Clicked on button page 4!
Current Page 4
Crawling data page 4
Clicked on button page 5!
Current Page 5
Crawling data page 5
Clicked on button page 6!
Current Page 6
Crawling data page 6
Clicked on button page 7!
Current Page 7
Crawling data page 7
Clicked on button page 8!
Current Page 8
Crawling data page 8
Clicked on button page 9!
Current Page 9
Crawling data page 9
Clicked on button page 10!
Current Page 10
Crawling data page 10
Clicked on button page 11!
Current Page 11
Crawling data page 11
Clicked on button page 12!
Current Page 12
Crawling data page 12
Clicked on button page 13!
Current Page 13
Crawling data page 13
Clicked on button page 14!
Current Page 14
Crawling data page 14
Clicked on button page 15!
Current Page 15
Crawling data page 15
Clicked on button page 16!
Current Page 16
Crawling data page 16
Clicked on button page 17!
Current Page 17
Crawling data page 17
Clicked on button page 18!
Current Page 18
Crawling data page 18
Clicked on button page 19!
Current Page 19
Crawling data page 19
Clicked on button page 20!
Current Page 20
Crawling data page 20
Clicked on button page 21!
Current Page 21
Crawling data page 21
Clicked on button page 22!
Current Page 22
Crawling data page 22
Clicked on button page 23!
Current Page 23
Crawling data page 23
Clicked on button page 24!
Current Page 24
Crawling data page 24
Clicked on button page 25!
Current Page 25
Crawling data page 25
Clicked on button page 26!
Current Page 26
Crawling data page 26
Clicked on button page 27!
Current Page 27
Crawling data page 27
Clicked on button page 28!
Current Page 28
Crawling data page 28
Clicked on button page 29!
Current Page 29
Crawling data page 29
Clicked on button page 30!
Current Page 30
Crawling data page 30
Clicked on button page 31!
Current Page 31
Crawling data page 31
Clicked on button page 32!
Current Page 32
Crawling data page 32
Clicked on button page 33!
Current Page 33
Crawling data page 33
Clicked on button page 34!
Current Page 34
Crawling data page 34
Clicked on button page 35!
Current Page 35
Crawling data page 35
Clicked on button page 36!
Current Page 36
Crawling data page 36
Clicked on button page 37!
Current Page 37
Crawling data page 37
Clicked on button page 38!
Current Page 38
Crawling data page 38
Clicked on button page 39!
Current Page 39
Crawling data page 39
Clicked on button page 40!
Current Page 40
Crawling data page 40
Clicked on button page 41!
Current Page 41
Crawling data page 41
Clicked on button page 42!
Current Page 42
Crawling data page 42
Clicked on button page 43!
Current Page 43
Crawling data page 43
Clicked on button page 44!
Current Page 44
Crawling data page 44
Clicked on button page 45!
Current Page 45
Crawling data page 45
Clicked on button page 46!
Current Page 46
Crawling data page 46
Clicked on button page 47!
Current Page 47
Crawling data page 47
Clicked on button page 48!
Current Page 48
Crawling data page 48
Clicked on button page 49!
Current Page 49
Crawling data page 49
Clicked on button page 50!
Current Page 50
Crawling data page 50
Clicked on button page 51!

i = 4
n = 14
elems = driver.find_element(By.XPATH,f'//*[@id="generalBody"]/table[1]/tbody/tr[{i}]/td[%d]'%n)
last_updated.append(elems.text)

In [17]:
df1 = pd.DataFrame(list(zip(games_titles,games_links, publishers, total_shipped, released_date, last_updated)),
                   columns = ['games_titles','games_links','publishers','total_shipped','released_date','last_updated'])

In [18]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   games_titles   2500 non-null   object
 1   games_links    2500 non-null   object
 2   publishers     2500 non-null   object
 3   total_shipped  2500 non-null   object
 4   released_date  2500 non-null   object
 5   last_updated   2500 non-null   object
dtypes: object(6)
memory usage: 117.3+ KB

In [19]:
df1['total_shipped'] = df1['total_shipped'].replace('N/A',None)
for i in range(0,len(df1)+1):
    try:
        df1['total_shipped'][i] = df1['total_shipped'][i].replace('.','.').replace('m','')
    except: 
        df1['total_shipped'][i] = None
df1['total_shipped']= df1['total_shipped'].astype(float)
#total_shipped is in Million

C:\Users\Rice\AppData\Local\Temp\ipykernel_10340\4092896219.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['total_shipped'][i] = df1['total_shipped'][i].replace('.','.').replace('m','')
C:\Users\Rice\AppData\Local\Temp\ipykernel_10340\4092896219.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['total_shipped'][i] = df1['total_shipped'][i].replace('.','.').replace('m','')
C:\Users\Rice\AppData\Local\Temp\ipykernel_10340\4092896219.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['total_shipped'][i] = df1['total_shipped'][i].replace('.','.').replace('m','')
C:\Users\Rice\AppData\Local\Temp\ipykernel_10340\4092896219.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['total_shipped'][i] = df1['total_shipped'][i].replace('.','.').replace('m','')
C:\Users\Rice\AppData\Local\Temp\ipykernel_10340\4092896219.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['total_shipped'][i] = df1['total_shipped'][i].replace('.','.').replace('m','')
C:\Users\Rice\AppData\Local\Temp\ipykernel_10340\4092896219.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['total_shipped'][i] = df1['total_shipped'][i].replace('.','.').replace('m','')
C:\Users\Rice\AppData\Local\Temp\ipykernel_10340\4092896219.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['total_shipped'][i] = df1['total_shipped'][i].replace('.','.').replace('m','')
C:\Users\Rice\AppData\Local\Temp\ipykernel_10340\4092896219.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['total_shipped'][i] = df1['total_shipped'][i].replace('.','.').replace('m','')
C:\Users\Rice\AppData\Local\Temp\ipykernel_10340\4092896219.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['total_shipped'][i] = df1['total_shipped'][i].replace('.','.').replace('m','')
C:\Users\Rice\AppData\Local\Temp\ipykernel_10340\4092896219.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['total_shipped'][i] = df1['total_shipped'][i].replace('.','.').replace('m','')
C:\Users\Rice\AppData\Local\Temp\ipykernel_10340\4092896219.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['total_shipped'][i] = df1['total_shipped'][i].replace('.','.').replace('m','')
C:\Users\Rice\AppData\Local\Temp\ipykernel_10340\4092896219.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['total_shipped'][i] = df1['total_shipped'][i].replace('.','.').replace('m','')
C:\Users\Rice\AppData\Local\Temp\ipykernel_10340\4092896219.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['total_shipped'][i] = df1['total_shipped'][i].replace('.','.').replace('m','')
C:\Users\Rice\AppData\Local\Temp\ipykernel_10340\4092896219.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['total_shipped'][i] = df1['total_shipped'][i].replace('.','.').replace('m','')
C:\Users\Rice\AppData\Local\Temp\ipykernel_10340\4092896219.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['total_shipped'][i] = df1['total_shipped'][i].replace('.','.').replace('m','')
C:\Users\Rice\AppData\Local\Temp\ipykernel_10340\4092896219.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['total_shipped'][i] = df1['total_shipped'][i].replace('.','.').replace('m','')
C:\Users\Rice\AppData\Local\Temp\ipykernel_10340\4092896219.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['total_shipped'][i] = df1['total_shipped'][i].replace('.','.').replace('m','')
C:\Users\Rice\AppData\Local\Temp\ipykernel_10340\4092896219.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['total_shipped'][i] = df1['total_shipped'][i].replace('.','.').replace('m','')
C:\Users\Rice\AppData\Local\Temp\ipykernel_10340\4092896219.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['total_shipped'][i] = df1['total_shipped'][i].replace('.','.').replace('m','')
C:\Users\Rice\AppData\Local\Temp\ipykernel_10340\4092896219.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['total_shipped'][i] = df1['total_shipped'][i].replace('.','.').replace('m','')
C:\Users\Rice\AppData\Local\Temp\ipykernel_10340\4092896219.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


In [20]:
#convert object to datetime:
def date_time(df,col):
    df[col] = df[col].replace('N/A',None)
    df[col] = pd.to_datetime(df[col]).dt.strftime('%Y-%m-%d')
    return df[col]

In [21]:
date_time(df1,'released_date')
date_time(df1,'last_updated')

C:\Users\Rice\AppData\Local\Temp\ipykernel_10340\2932832993.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col]).dt.strftime('%Y-%m-%d')
C:\Users\Rice\AppData\Local\Temp\ipykernel_10340\2932832993.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col]).dt.strftime('%Y-%m-%d')

0       2020-02-27
1       2020-02-03
2       2020-02-03
3       2020-02-03
4       2020-02-20
           ...
2495    2018-05-24
2496           NaN
2497           NaN
2498    2022-10-18
2499    2021-01-20
Name: last_updated, Length: 2500, dtype: object

In [22]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   games_titles   2500 non-null   object
 1   games_links    2500 non-null   object
 2   publishers     2500 non-null   object
 3   total_shipped  1274 non-null   float64
 4   released_date  2475 non-null   object
 5   last_updated   1206 non-null   object
dtypes: float64(1), object(5)
memory usage: 117.3+ KB

In [23]:
df1.select_dtypes(include = 'object').describe()

,games_titles,games_links,publishers,released_date,last_updated
count,2500,2500,2500,2475,1206
unique,1793,2150,249,1328,462
top,Teenage Mutant Ninja Turtles,https://www.vgchartz.com/game/227894/the-lord-...,Nintendo,2009-09-15,2020-02-03
freq,7,2,255,13,13

In [24]:
df1.describe()

       total_shipped
count    1274.000000
mean       13.608854
std        39.423843
min         0.550000
25%         1.500000
50%         3.000000
75%        12.690000
max       520.000000