In [21]:
import pandas as pd
import numpy as np
from selenium import webdriver
from selenium.webdriver.edge.service import Service
from selenium.webdriver.common.by import By
from time import sleep
import random
from selenium.common.exceptions import NoSuchElementException, ElementNotInteractableException
import seaborn as sns
from matplotlib import pyplot as plt

In [11]:
edgeService = Service(driver_path_env_key= 'Driver_Notes/msedgedriver.exe')
options = webdriver.EdgeOptions()
options.add_argument("--auto-open-devtools-for-tabs")
options.add_argument('start-maximized')
options.add_argument('--headless')
options.add_argument('inprivate')

In [12]:
driver = webdriver.Edge(service= edgeService,options=options)
driver.get('https://trends.google.com/trending?geo=VN&hl=vi&hours=168&sort=recency')
sleep(random.randint(5,10))

elems = driver.find_elements(By.CSS_SELECTOR, '.mZ3RIc')
title = [elem.text for elem in elems]

driver.execute_script("window.dispatchEvent(new Event('resize'));")
elems_num_searches = driver.find_elements(By.CSS_SELECTOR, '.qNpYPd')
num_searches = [num.text for num in elems_num_searches]

elems_activate_hours = driver.find_elements(By.CSS_SELECTOR, '.A7jE4')
hours = [hour.text for hour in elems_activate_hours]

In [13]:
max_search = driver.find_element(By.CSS_SELECTOR, '.enOdEe-wZVHld-gruSEe-j4LONd')
num_max = max_search.text
max_page = (int(num_max[-3:])//25)+1
print(num_max,max_page)

1–25 trong tổng số 475 20

button_selector = '/html/body/c-wiz/div/div[5]/div[1]/c-wiz/div/div[2]/div[1]/div[1]/div[2]/div/div[2]/span[3]/button/span[2]'
button = driver.find_element('xpath', button_selector)
driver.execute_script("arguments[0].click();", button)
elems = driver.find_elements(By.CSS_SELECTOR, '.mZ3RIc')
title1.extend(elem.text for elem in elems)

In [14]:
count = 1
button_selector = '/html/body/c-wiz/div/div[5]/div[1]/c-wiz/div/div[2]/div[1]/div[1]/div[2]/div/div[2]/span[3]/button/span[2]'
title, num_searches, hours = [], [], []
while count <= max_page:
    try:
        print('Crawl Page '+ str(count))
        #crawl data in the current page
        elems = driver.find_elements(By.CSS_SELECTOR, '.mZ3RIc')
        title.extend(elem.text for elem in elems)
        sleep(3)
        elems_num_searches = driver.find_elements(By.CSS_SELECTOR, '.lqv0Cb')
        num_searches.extend(num.text for num in elems_num_searches)
        elems_activate_hours = driver.find_elements(By.CSS_SELECTOR, '.vdw3Ld')
        hours.extend(hour.text for hour in elems_activate_hours)
        #click next page
        button = driver.find_element('xpath', button_selector)
        driver.execute_script("arguments[0].click();", button)
        print('Clicked on button next page!')
        sleep(random.randint(5,10))
        count += 1;
    except ElementNotInteractableException:
        print('Element Not Interactable Exception!') 
        break

Crawl Page 1
Clicked on button next page!
Crawl Page 2
Clicked on button next page!
Crawl Page 3
Clicked on button next page!
Crawl Page 4
Clicked on button next page!
Crawl Page 5
Clicked on button next page!
Crawl Page 6
Clicked on button next page!
Crawl Page 7
Clicked on button next page!
Crawl Page 8
Clicked on button next page!
Crawl Page 9
Clicked on button next page!
Crawl Page 10
Clicked on button next page!
Crawl Page 11
Clicked on button next page!
Crawl Page 12
Clicked on button next page!
Crawl Page 13
Clicked on button next page!
Crawl Page 14
Clicked on button next page!
Crawl Page 15
Clicked on button next page!
Crawl Page 16
Clicked on button next page!
Crawl Page 17
Clicked on button next page!
Crawl Page 18
Clicked on button next page!
Crawl Page 19
Clicked on button next page!
Crawl Page 20
Clicked on button next page!

In [15]:
df1 = pd.DataFrame(list(zip(title,num_searches,hours)), columns = ['title','num_searches','activate_hours'])

In [16]:
for i in range(len(df1)):
    df1['num_searches'][i]= df1['num_searches'][i][0:4].strip().replace(' N','000').replace('Tr','000000').replace('+','').replace(' ','')
df1['num_searches'] = df1['num_searches'].astype(float)

C:\Users\Rice\AppData\Local\Temp\ipykernel_1432\3130479989.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['num_searches'][i]= df1['num_searches'][i][0:4].strip().replace(' N','000').replace('Tr','000000').replace('+','').replace(' ','')

In [17]:
df1.rename(columns = {'activate_hours':'start_hours'},inplace=True)

In [18]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         500 non-null    object
 1   num_searches  500 non-null    float64
 2   start_hours   500 non-null    object
dtypes: float64(1), object(2)
memory usage: 11.8+ KB

In [19]:
df1.describe()

       num_searches
count    500.000000
mean    3337.400000
std     8267.122345
min      100.000000
25%      200.000000
50%      500.000000
75%     2000.000000
max    50000.000000

In [20]:
df1.select_dtypes(include=object).describe()

          title   start_hours
count       500           500
unique      448            26
top     weather  6 ngày trước
freq          4           110

In [31]:
df1

                            title  num_searches    start_hours
0              fifa the best 2024         100.0  50 phút trước
1                     carabao cup         100.0    1 giờ trước
2            giá xăng dầu hôm nay         500.0    1 giờ trước
3            juventus vs cagliari         100.0    3 giờ trước
4                     pengu token         100.0    3 giờ trước
..                            ...           ...            ...
495   leipzig đấu với aston villa       20000.0   6 ngày trước
496  atalanta đấu với real madrid         100.0   6 ngày trước
497      leverkusen đấu với inter       10000.0   6 ngày trước
498                      telegram         200.0   6 ngày trước
499               champion league        1000.0   6 ngày trước

[500 rows x 3 columns]

convert_num(df1,'num_searches')