In [ ]:
import pandas as pd
import numpy as np
from selenium import webdriver
from selenium.webdriver.edge.service import Service
from selenium.webdriver.common.by import By
from time import sleep
import random
from selenium.common.exceptions import NoSuchElementException, ElementNotInteractableException
import msedgedriver

In [89]:
edgeService = msedgedriver.install()
options = webdriver.EdgeOptions()
options.add_argument("--auto-open-devtools-for-tabs")
options.add_argument('--headless')

your edge version is
131.0.2903.70
[Errno 2] No such file or directory: 'C:\\ProgramData\\msedge_version.txt'
downloading the edgedriver for this version
File Name                                             Modified             Size
Driver_Notes/                                  2024-11-25 17:46:02            0
Driver_Notes/credits.html                      2024-11-25 14:00:40      9993808
Driver_Notes/EULA                              2024-11-25 13:13:52        10998
Driver_Notes/LICENSE                           2024-11-25 13:13:26         1615
msedgedriver.exe                               2024-11-25 17:47:34     15537736
extracting...
Extracted
ready to go!

In [90]:
driver = webdriver.Edge(service= edgeService,options=options)
driver.get('https://trends.google.com/trending?geo=VN&hl=vi&hours=168&sort=recency')
sleep(random.randint(5,10))

elems = driver.find_elements(By.CSS_SELECTOR, '.mZ3RIc')
title = [elem.text for elem in elems]

driver.execute_script("window.dispatchEvent(new Event('resize'));")
elems_num_searches = driver.find_elements(By.CSS_SELECTOR, '.qNpYPd')
num_searches = [num.text for num in elems_num_searches]

elems_activate_hours = driver.find_elements(By.CSS_SELECTOR, '.A7jE4')
hours = [hour.text for hour in elems_activate_hours]

In [91]:
max_search = driver.find_element(By.CSS_SELECTOR, '.enOdEe-wZVHld-gruSEe-j4LONd')
num_max = max_search.text
max_page = (int(num_max[-3:])//25)+1
print(num_max,max_page)

1–25 trong tổng số 438 18

button_selector = '/html/body/c-wiz/div/div[5]/div[1]/c-wiz/div/div[2]/div[1]/div[1]/div[2]/div/div[2]/span[3]/button/span[2]'
button = driver.find_element('xpath', button_selector)
driver.execute_script("arguments[0].click();", button)
elems = driver.find_elements(By.CSS_SELECTOR, '.mZ3RIc')
title1.extend(elem.text for elem in elems)

In [92]:
count = 1
button_selector = '/html/body/c-wiz/div/div[5]/div[1]/c-wiz/div/div[2]/div[1]/div[1]/div[2]/div/div[2]/span[3]/button/span[2]'
title, num_searches, hours = [], [], []
while count <= max_page:
    try:
        print('Crawl Page '+ str(count))
        #crawl data in the current page
        elems = driver.find_elements(By.CSS_SELECTOR, '.mZ3RIc')
        title.extend(elem.text for elem in elems)
        sleep(3)
        elems_num_searches = driver.find_elements(By.CSS_SELECTOR, '.qNpYPd')
        num_searches.extend(num.text for num in elems_num_searches)
        elems_activate_hours = driver.find_elements(By.CSS_SELECTOR, '.A7jE4')
        hours.extend(hour.text for hour in elems_activate_hours)
        #click next page
        button = driver.find_element('xpath', button_selector)
        driver.execute_script("arguments[0].click();", button)
        print('Clicked on button next page!')
        sleep(random.randint(5,10))
        count += 1;
    except ElementNotInteractableException:
        print('Element Not Interactable Exception!') 
        break

Crawl Page 1
Clicked on button next page!
Crawl Page 2
Clicked on button next page!
Crawl Page 3
Clicked on button next page!
Crawl Page 4
Clicked on button next page!
Crawl Page 5
Clicked on button next page!
Crawl Page 6
Clicked on button next page!
Crawl Page 7
Clicked on button next page!
Crawl Page 8
Clicked on button next page!
Crawl Page 9
Clicked on button next page!
Crawl Page 10
Clicked on button next page!
Crawl Page 11
Clicked on button next page!
Crawl Page 12
Clicked on button next page!
Crawl Page 13
Clicked on button next page!
Crawl Page 14
Clicked on button next page!
Crawl Page 15
Clicked on button next page!
Crawl Page 16
Clicked on button next page!
Crawl Page 17
Clicked on button next page!
Crawl Page 18
Clicked on button next page!

In [98]:
df1 = pd.DataFrame(list(zip(title,num_searches,hours)), columns = ['title','num_searches','activate_hours'])

In [101]:
for i in range(len(df1)):
    df1['num_searches'][i]= df1['num_searches'][i][0:4].strip().replace(' N','000').replace('Tr','000000').replace('+','').replace(' ','')
df1['num_searches'] = df1['num_searches'].astype(float)

C:\Users\Rice\AppData\Local\Temp\ipykernel_6020\3130479989.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1['num_searches'][i]= df1['num_searches'][i][0:4].strip().replace(' N','000').replace('Tr','000000').replace('+','').replace(' ','')

In [102]:
df1.rename(columns = {'activate_hours':'start_hours'},inplace=True)

In [103]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438 entries, 0 to 437
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         438 non-null    object
 1   num_searches  438 non-null    float64
 2   start_hours   438 non-null    object
dtypes: float64(1), object(2)
memory usage: 10.4+ KB

In [105]:
df1.describe()

       num_searches
count    438.000000
mean    1021.689498
std     1323.786910
min      100.000000
25%      200.000000
50%      500.000000
75%     1000.000000
max     5000.000000

In [104]:
df1.select_dtypes(include=object).describe()

          title   start_hours
count       438           438
unique      420            28
top     weather  6 ngày trước
freq          3           104

convert_num(df1,'num_searches')